name: Build-Test-Deploy

on: 
    push:
        - master
        
jobs:
    Build-Job:
        runs-on: windows-latest
        name: Making builds
        steps:
            - uses: actions/checkout@v1
            - name: Install surge
              uses: actions/setup-node@v1
              with:
                node-version:12
            - run: npm install -g surge
        
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
