name: Build-Test-Deploy

on: 
    push:
        - master
        
jobs:
    Build-Job:
        runs-on: windows-latest
        name: Making builds
        steps:
            - uses: actions/checkout@v1
            - name: Install surge
              uses: actions/setup-node@v1
              with:
                node-version:12
            - run: npm install -g surge
        
